[tox]
envlist = py311, ruff, ty

[testenv:ruff]
dependency_groups =
    lint

recreate = False
setenv =
    PYTHONPATH = {toxinidir}/src
commands = ruff check --show-fixes src

[testenv:ty]
dependency_groups =
    lint

recreate = False
setenv =
    PYTHONPATH = {toxinidir}/src
commands = ty check src

[testenv]
basepython = py311
passenv =
    TC_HOST
requires =
    keyring
    tox-uv

setenv =
    PYTHONPATH = {toxinidir}/src

[testenv:py311]
dependency_groups =
    test
commands =
    pytest --basetemp={envtmpdir} --cov=src --cov-report=term-missing tests
